### ISSUE TITLE
Could you please confirm ESI Courseware report?

### ISSUE THREAD

**Issue by hiryamada** [ESI-EMEA/ESI-Courseware_PowerBI#1]
![image](https://user-images.githubusercontent.com/71864722/160092689-0fb85381-8a44-45bc-a0bf-c26d45ce5300.png)
I had created 100+ feedbacks but I can't find it on the report.

**Comment by unaihuete93** [comment]
Hi @hiryamada , the reports are not supporting localized versions :(  It looks for SE BUG work items in ADO , excluding Skillpipe related ones ( as it will be deprecated) 

I can see all work items you opened , but the Localization ones and Skillpipe related Bugs are not shown in the report
![image](https://user-images.githubusercontent.com/64772417/161064558-8af09aea-0cfd-40b0-b3e3-06008035ab3b.png)

This is a filter that is being applied 
![image](https://user-images.githubusercontent.com/64772417/161064838-4285dd88-f544-4d4d-a953-d78b5e8feae4.png)

**Comment by hiryamada** [comment]
Hi @unaihuete93 , thank you for that information! I can understand.
